"""add_height_weight_to_patients

Revision ID: 0fe920ec6340
Revises: 927eb5f8e267
Create Date: 2026-07-22 15:46:38.299210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0fe920ec6340'
down_revision: Union[str, None] = '927eb5f8e267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_availability_change_requests_user_id'), 'availability_change_requests', ['user_id'], unique=False)
    op.add_column('patients', sa.Column('height', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('weight', sa.String(length=20), nullable=True))
    op.alter_column('patients', 'is_profile_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'is_profile_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.drop_column('patients', 'weight')
    op.drop_column('patients', 'height')
    op.drop_index(op.f('ix_availability_change_requests_user_id'), table_name='availability_change_requests')
    # ### end Alembic commands ###
