"""create_invoices_and_payments

Revision ID: 2119844de640
Revises: 689ddcda500a
Create Date: 2026-07-13 11:25:04.703745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2119844de640'
down_revision: Union[str, None] = '689ddcda500a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
