"""add_followup_columns

Revision ID: 47805c2ea364
Revises: 0fe920ec6340
Create Date: 2026-07-29 17:50:29.848717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47805c2ea364'
down_revision: Union[str, None] = '0fe920ec6340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('followup_advised', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('consultations', sa.Column('followup_after_days', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'followup_after_days')
    op.drop_column('consultations', 'followup_advised')
    # ### end Alembic commands ###
