"""add_appointment_reschedule_cancel_fields

Revision ID: 54c41ea6dc05
Revises: 8181e8eacd95
Create Date: 2026-07-13 16:30:37.551219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '54c41ea6dc05'
down_revision: Union[str, None] = '8181e8eacd95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('reschedule_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('appointments', sa.Column('cancelled_by', sa.String(length=50), nullable=True))
    op.add_column('appointments', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('patients', 'notification_email',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patients', 'notification_sms',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patients', 'notification_whatsapp',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('patients', 'notification_push',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'notification_push',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('patients', 'notification_whatsapp',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('patients', 'notification_sms',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('patients', 'notification_email',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('appointments', 'cancelled_at')
    op.drop_column('appointments', 'cancel_reason')
    op.drop_column('appointments', 'cancelled_by')
    op.drop_column('appointments', 'reschedule_count')
    # ### end Alembic commands ###
