"""add_address_to_patient

Revision ID: 675ba0f01873
Revises: eeef5f49c5a4
Create Date: 2026-07-13 10:41:45.223455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '675ba0f01873'
down_revision: Union[str, None] = 'eeef5f49c5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'address')
    # ### end Alembic commands ###
