"""add_patient_preferences

Revision ID: 8181e8eacd95
Revises: b0adf0da459c
Create Date: 2026-07-13 16:29:30.731240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8181e8eacd95'
down_revision: Union[str, None] = 'b0adf0da459c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('notification_email', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('patients', sa.Column('notification_sms', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('patients', sa.Column('notification_whatsapp', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('patients', sa.Column('notification_push', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('patients', sa.Column('preferred_doctor_id', sa.UUID(), nullable=True))
    op.add_column('patients', sa.Column('consultation_preference', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'patients', 'doctors', ['preferred_doctor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'consultation_preference')
    op.drop_column('patients', 'preferred_doctor_id')
    op.drop_column('patients', 'notification_push')
    op.drop_column('patients', 'notification_whatsapp')
    op.drop_column('patients', 'notification_sms')
    op.drop_column('patients', 'notification_email')
    op.drop_column('patients', 'language')
    # ### end Alembic commands ###
