"""add_doctor_availability_metadata

Revision ID: 927eb5f8e267
Revises: 54c41ea6dc05
Create Date: 2026-07-14 12:59:48.506578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '927eb5f8e267'
down_revision: Union[str, None] = '54c41ea6dc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('availability_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'availability_metadata')
    # ### end Alembic commands ###
