"""add_emergency_relation_and_insurance_fields

Revision ID: aa6ea75647ed
Revises: 675ba0f01873
Create Date: 2026-07-13 10:46:53.233846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa6ea75647ed'
down_revision: Union[str, None] = '675ba0f01873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('emergency_contact_relation', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('insurance_provider', sa.String(length=200), nullable=True))
    op.add_column('patients', sa.Column('insurance_policy_no', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('preferred_payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'preferred_payment_method')
    op.drop_column('patients', 'insurance_policy_no')
    op.drop_column('patients', 'insurance_provider')
    op.drop_column('patients', 'emergency_contact_relation')
    # ### end Alembic commands ###
